### ISSUE TITLE
Was this talk recorded?

### ISSUE THREAD

**Issue by JulianBissekkou** [mit-mit/ffi-talk#7]
I found this repository and i was wondering if the talk was recorded. I would love to watch it or go through the slides.
Have a nice day ✌🏽

**Comment by ppsimn** [comment]
I know that /sqlite_example was used for demonstration in a YouTube video on Flutter YT Channel.
link to video: ["C interoperability with Dart FFI | Session"](https://www.youtube.com/watch?v=2MMK7YoFgaA)

**Comment by mit-mit** [comment]
Yeah, that talk is the one!
